### PR TITLE
Fix invalid type imports

### PR DESCRIPTION
**Pull request by samchungy**
### What does this PR do?
- Fixes invalid type imports introduced in https://github.com/DataDog/datadog-lambda-js/pull/429

### Motivation
Datadog lambda js is throwing a build error:
https://github.com/seek-oss/skuba/actions/runs/6992350107/job/19023877986?pr=1326#step:4:288

### Testing Guidelines

Build using tsc/lint locally

### Types of Changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [x] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Comment by samchungy** [comment]
Hey @astuyve could I get a ✅ on this one :)

**Comment by astuyve** [comment]
Hey I'm at re:Invent right now and can't look, but will ask someone to check in!

Thanks!

**Review by duncanista — APPROVED** [review]
Thanks for fixing this – sorry for the inconvenience, LGTM!

**Comment by samchungy** [comment]
Oh looks like those tests don't work for non datadog employees 😕. Not sure how to resolve this @duncanista . Happy for you to just copy the changes into another branch if that works

**Comment by duncanista** [comment]
@samchungy I'll run them in my machine from this PR, they should pass from my point of view, so we can override that – if this is business critical for you, please raise a ticket with us so we can escalate and make a release for this, be sure to mention this PR, and this comment. 

We normally wouldn't request this, but due to an active Code Freeze on our side, we are limited on the releases!

**Comment by samchungy** [comment]
> @samchungy I'll run them in my machine from this PR, they should pass from my point of view, so we can override that – if this is business critical for you, please raise a ticket with us so we can escalate and make a release for this, be sure to mention this PR, and this comment.
> 
> We normally wouldn't request this, but due to an active Code Freeze on our side, we are limited on the releases!

All good, I understand. I'll just pin it on our side for now

**Comment by astuyve** [comment]
Thanks so much @samchungy!!!

**Pull request merged**
