### PR TITLE
feat: Remove extension hello check as it's redundant

### PR DESCRIPTION
**Pull request by astuyve**
### What does this PR do?
Checking the file presence is enough, start order is enforced by the lambda runtime.

### Types of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [ ] This PR passes the integration tests (ask a Datadog member to run the tests)

### CODE REVIEW

**Review by duncanista — APPROVED** [review]
LGTM

**Comment by purple4reina** [comment]
So. I know the extension specifically uses the call to `Hello` to determine if there's a tracing layer present. See https://github.com/DataDog/datadog-agent/blob/11e8ea8b5455530ba8afa8ef1831d179c5523479/pkg/serverless/daemon/routes.go#L29

**Comment by astuyve** [comment]
We do, but the library never calls `start-invocation`, so I assume the call to `enrichInferredSpan()` never happens or happens but the result is never used. [source](https://github.com/DataDog/datadog-agent/blob/11e8ea8b5455530ba8afa8ef1831d179c5523479/pkg/serverless/invocationlifecycle/init.go#L28).

We can see with this build, there are no duplicate spans. And we have made this change in Python already.

**Comment by purple4reina** [comment]
> We do, but the library never calls `start-invocation`, so I assume the call to `enrichInferredSpan()` never happens or happens but the result is never used. [source](https://github.com/DataDog/datadog-agent/blob/11e8ea8b5455530ba8afa8ef1831d179c5523479/pkg/serverless/invocationlifecycle/init.go#L28).
> 
> We can see with this build, there are no duplicate spans. And we have made this change in Python already.

Ah, yes I see now. Thanks for the explanation. We can probably just go ahead and delete that code from the extension then yeah?

**Pull request merged**
